services:
  api:
    image: rag-api
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=your_key_here

  ui:
    image: streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
